// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xFood.Infrastructure.Persistence;

#nullable disable

namespace xFood.Infrastructure.Migrations
{
    // Snapshot do modelo atual do DbContext (gerado pelo EF Core).
    [DbContext(typeof(xFoodDbContext))]
    partial class xFoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Configurações gerais do modelo.
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Entidade Category.
            modelBuilder.Entity("xFood.Domain.Entities.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("nvarchar(80)");

                b.HasKey("Id");

                b.HasIndex("Name").IsUnique();

                b.ToTable("Category", (string)null);
            });

            // Entidade Product.
            modelBuilder.Entity("xFood.Domain.Entities.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CategoryId").HasColumnType("int");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("ImageUrl")
                    .HasMaxLength(2048)
                    .HasColumnType("nvarchar(2048)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.Property<decimal>("Price")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("Stock")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("Name");
                b.HasIndex("CategoryId", "Name");

                b.ToTable("Product", (string)null);
            });

            // Entidade TypeUser.
            modelBuilder.Entity("xFood.Domain.Entities.TypeUser", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.HasKey("Id");

                b.ToTable("TypeUser", (string)null);
            });

            // Entidade User.
            modelBuilder.Entity("xFood.Domain.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<bool>("Active")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<DateTime>("DateBirth")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<int>("TypeUserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("TypeUserId");

                b.ToTable("User", (string)null);
            });

            // Relacionamento Product -> Category.
            modelBuilder.Entity("xFood.Domain.Entities.Product", b =>
            {
                b.HasOne("xFood.Domain.Entities.Category", "Category")
                    .WithMany("Products")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Category");
            });

            // Relacionamento User -> TypeUser.
            modelBuilder.Entity("xFood.Domain.Entities.User", b =>
            {
                b.HasOne("xFood.Domain.Entities.TypeUser", "TypeUser")
                    .WithMany("Users")
                    .HasForeignKey("TypeUserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("TypeUser");
            });

            // Navegações.
            modelBuilder.Entity("xFood.Domain.Entities.Category", b =>
            {
                b.Navigation("Products");
            });

            modelBuilder.Entity("xFood.Domain.Entities.TypeUser", b =>
            {
                b.Navigation("Users");
            });
#pragma warning restore 612, 618
        }
    }
}
